# Generated by Django 2.1.1 on 2018-10-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minerals', '0002_mineral_crystal_habit'),
    ]

    operations = [
        migrations.AddField(
            model_name='mineral',
            name='specific_gravity',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
